DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

DROP SCHEMA IF EXISTS infsc CASCADE;
DROP SCHEMA IF EXISTS infsc_priv CASCADE;

DROP ROLE IF EXISTS infsc_anon;
DROP ROLE IF EXISTS infsc_user;
DROP ROLE IF EXISTS infsc_server;

DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP EXTENSION IF EXISTS "pgcrypto" CASCADE;
